In [1]:
import numpy as np


In [2]:
np.zeros(8)

array([0., 0., 0., 0., 0., 0., 0., 0.])

In [3]:
np.linspace(10,1,10)

array([10.,  9.,  8.,  7.,  6.,  5.,  4.,  3.,  2.,  1.])

In [4]:
a = np.array([[1,2,3],[4,5,6],[7,8,9]])
a[:,1]
a[1]

array([4, 5, 6])

In [5]:
np.random.seed(20)
np.random.rand(8,3)


array([[0.5881308 , 0.89771373, 0.89153073],
       [0.81583748, 0.03588959, 0.69175758],
       [0.37868094, 0.51851095, 0.65795147],
       [0.19385022, 0.2723164 , 0.71860593],
       [0.78300361, 0.85032764, 0.77524489],
       [0.03666431, 0.11669374, 0.7512807 ],
       [0.23921822, 0.25480601, 0.85762553],
       [0.94977903, 0.56168686, 0.17878052]])

In [6]:
np.random.randn(8,3)


array([[-0.0441948 ,  1.56763255,  1.05110868],
       [ 0.40636843, -0.1686461 , -3.18970279],
       [ 1.12013226,  1.33277821, -0.24333877],
       [-0.13003071, -0.10901737,  1.55618644],
       [ 0.12877835, -2.06694872, -0.88549315],
       [-1.10457948,  0.93286635,  2.059838  ],
       [-0.93493796, -1.61299022,  0.52706972],
       [-1.55110074,  0.32961334, -1.13652654]])

In [7]:
b = np.random.randint(3,6,10)
b

array([5, 5, 4, 4, 5, 4, 3, 5, 5, 3])

In [8]:
b + 99

array([104, 104, 103, 103, 104, 103, 102, 104, 104, 102])

In [9]:
a1 = np.random.randint(3,6,10)
a2 = np.random.randint(3,6,10)

In [10]:
a1[a2 > a1]


array([3, 3, 4, 4])

In [11]:
a1.std()


0.8

In [12]:
a1.sum()


36

In [13]:
a1.min()


3